services:
  mysql:
    image: mysql:8.0
    container_name: avivo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: avivo_users
    ports:
      - "3306:3306"
    volumes:
      - ./sql-data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avivo-api
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: avivo_users
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: sh -c "npm run seed; node dist/server.js"

networks:
  default:
